### ISSUE TITLE
Browserslist: caniuse-lite is outdated. Please run. (ERROR)

### ISSUE THREAD

**Issue by thefubon** [m-Ryan/RyanCMS#23]
```js
[client] Browserslist: caniuse-lite is outdated. Please run:
[client] npx browserslist@latest --update-db
```

```internal/modules/cjs/loader.js:969
[client]   throw err;
[client]   ^
[client] 
[client] Error: Cannot find module 'caniuse-lite/dist/unpacker/agents'
[client] Require stack:
[client] - /home/fubon/public_html/node_modules/browserslist/index.js
[client] - /home/fubon/public_html/node_modules/postcss-browser-comments/index.cjs.js
[client] - /home/fubon/public_html/node_modules/postcss-normalize/index.cjs.js
[client] - /home/fubon/public_html/config/webpack.config.js
[client] - /home/fubon/public_html/scripts/start.js
[client]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
[client]     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
[client]     at Module.require (internal/modules/cjs/loader.js:1026:19)
[client]     at require (internal/modules/cjs/helpers.js:72:18)
[client]     at Object.<anonymous> (/home/fubon/public_html/node_modules/browserslist/index.js:2:14)
[client]     at Module._compile (internal/modules/cjs/loader.js:1138:30)
[client]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
[client]     at Module.load (internal/modules/cjs/loader.js:986:32)
[client]     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
[client]     at Module.require (internal/modules/cjs/loader.js:1026:19) {
[client]   code: 'MODULE_NOT_FOUND',
[client]   requireStack: [
[client]     '/home/fubon/public_html/node_modules/browserslist/index.js',
[client]     '/home/fubon/public_html/node_modules/postcss-browser-comments/index.cjs.js',
[client]     '/home/fubon/public_html/node_modules/postcss-normalize/index.cjs.js',
[client]     '/home/fubon/public_html/config/webpack.config.js',
[client]     '/home/fubon/public_html/scripts/start.js'
[client]   ]
[client] }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[client] yarn start:client exited with code 1```

**Comment by thefubon** [comment]
```
Error: Command failed: npx browserslist
Cannot find module 'caniuse-lite/dist/unpacker/agents'
Require stack:
- /home/fubon/public_html/node_modules/browserslist/index.js
- /home/fubon/public_html/node_modules/browserslist/cli.js

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at getBrowsersList (/root/.npm/_npx/32634/lib/node_modules/browserslist/update-db.js:66:23)
    at updateDB (/root/.npm/_npx/32634/lib/node_modules/browserslist/update-db.js:304:29)
    at Object.<anonymous> (/root/.npm/_npx/32634/lib/node_modules/browserslist/cli.js:40:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

Problem with browser list retrieval.
Target browser changes won’t be shown.
```

**Comment by thefubon** [comment]
```
ryan-cms@0.1.0 /home/fubon/public_html
├── UNMET PEER DEPENDENCY @nestjs/common@7.2.0
├── UNMET PEER DEPENDENCY @nestjs/core@7.2.0
├── UNMET PEER DEPENDENCY babel-eslint@9.0.0
├── UNMET PEER DEPENDENCY browserify@>= 10.x
├── UNMET PEER DEPENDENCY canvas@^2.5.0
├── UNMET PEER DEPENDENCY eslint@6.8.0
├── UNMET PEER DEPENDENCY jest@>=22 <24
└─┬ postcss-preset-env@6.3.1
  └── caniuse-lite@1.0.30001256 
```

**Comment by m-Ryan** [comment]
![image](https://user-images.githubusercontent.com/20615214/132990449-5db7de76-915a-4316-938a-43635e98b948.png)

It seems that there is no problem, please reinstall the dependencies.
```bash
yarn --forece

```
