### ISSUE TITLE
(Error) yarn production

### ISSUE THREAD

**Issue by thefubon** [m-Ryan/RyanCMS#24]
```
root@webuzo:/home/fubon/public_html# yarn production
yarn run v1.22.5
$ cross-env NODE_ENV=production ts-node -r tsconfig-paths/register app/main.ts
[webpack build start]  - 检测到未打包前端目录，将自动打包

> ryan-cms@0.1.0 build /home/fubon/public_html
> node scripts/build.js

Creating an optimized production build...
^[[DCompiled successfully.

File sizes after gzip:

  234.08 KB  build/static/js/common.95f4fb95.chunk.js
  70.72 KB   build/static/js/vendors.44fbc907.chunk.js
  68.71 KB   build/static/js/antd.4e7456e3.chunk.js
  42.84 KB   build/static/css/main.3f6e7a5a.chunk.css
  24.34 KB   build/static/js/main.dcfa77c8.chunk.js
  4.15 KB    build/theme.js
  1.18 KB    build/static/js/runtime-main.8363748a.js
  427 B      build/static/css/common.88a603a2.chunk.css
  310 B      build/static/js/markdownRender.bd74409a.chunk.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

[webpack build end]  - 前端目录已打包完成
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [NestFactory] Starting Nest application...
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] TypeOrmModule dependencies initialized +92ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] CommonModule dependencies initialized +1ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] HttpModule dependencies initialized +1ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] UserModule dependencies initialized +2ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] TagModule dependencies initialized +1ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] ArticleModule dependencies initialized +0ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] CategoryModule dependencies initialized +1ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] AlbumModule dependencies initialized +0ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] NoticeModule dependencies initialized +1ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] CommentModule dependencies initialized +0ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] UploadModule dependencies initialized +1ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] MapModule dependencies initialized +1ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] ToolsModule dependencies initialized +0ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [InstanceLoader] EmailModule dependencies initialized +0ms
[Nest] 1399   - 09/11/2021, 8:17:54 AM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +55ms
Error: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ryancms'@'localhost' to database 'ryancms'
    at Handshake.Sequence._packetToError (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    --------------------
    at Protocol._enqueue (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/fubon/public_html/node_modules/mysql/lib/Pool.js:48:16)
    at /home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:884:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:881:16)
    at MysqlDriver.<anonymous> (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:343:36)
    at step (/home/fubon/public_html/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/fubon/public_html/node_modules/tslib/tslib.js:122:57)
[Nest] 1399   - 09/11/2021, 8:17:57 AM   [TypeOrmModule] Unable to connect to the database. Retrying (2)... +3009ms
Error: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ryancms'@'localhost' to database 'ryancms'
    at Handshake.Sequence._packetToError (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    --------------------
    at Protocol._enqueue (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/fubon/public_html/node_modules/mysql/lib/Pool.js:48:16)
    at /home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:884:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:881:16)
    at MysqlDriver.<anonymous> (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:343:36)
    at step (/home/fubon/public_html/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/fubon/public_html/node_modules/tslib/tslib.js:122:57)
[Nest] 1399   - 09/11/2021, 8:18:00 AM   [TypeOrmModule] Unable to connect to the database. Retrying (3)... +3009ms
Error: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ryancms'@'localhost' to database 'ryancms'
    at Handshake.Sequence._packetToError (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    --------------------
    at Protocol._enqueue (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/fubon/public_html/node_modules/mysql/lib/Pool.js:48:16)
    at /home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:884:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:881:16)
    at MysqlDriver.<anonymous> (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:343:36)
    at step (/home/fubon/public_html/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/fubon/public_html/node_modules/tslib/tslib.js:122:57)
[Nest] 1399   - 09/11/2021, 8:18:03 AM   [TypeOrmModule] Unable to connect to the database. Retrying (4)... +3006ms
Error: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ryancms'@'localhost' to database 'ryancms'
    at Handshake.Sequence._packetToError (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    --------------------
    at Protocol._enqueue (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/fubon/public_html/node_modules/mysql/lib/Pool.js:48:16)
    at /home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:884:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:881:16)
    at MysqlDriver.<anonymous> (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:343:36)
    at step (/home/fubon/public_html/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/fubon/public_html/node_modules/tslib/tslib.js:122:57)
[Nest] 1399   - 09/11/2021, 8:18:06 AM   [TypeOrmModule] Unable to connect to the database. Retrying (5)... +3010ms
Error: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ryancms'@'localhost' to database 'ryancms'
    at Handshake.Sequence._packetToError (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    --------------------
    at Protocol._enqueue (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/fubon/public_html/node_modules/mysql/lib/Pool.js:48:16)
    at /home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:884:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:881:16)
    at MysqlDriver.<anonymous> (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:343:36)
    at step (/home/fubon/public_html/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/fubon/public_html/node_modules/tslib/tslib.js:122:57)
[Nest] 1399   - 09/11/2021, 8:18:10 AM   [TypeOrmModule] Unable to connect to the database. Retrying (6)... +3009ms
Error: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ryancms'@'localhost' to database 'ryancms'
    at Handshake.Sequence._packetToError (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    --------------------
    at Protocol._enqueue (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/fubon/public_html/node_modules/mysql/lib/Pool.js:48:16)
    at /home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:884:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:881:16)
    at MysqlDriver.<anonymous> (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:343:36)
    at step (/home/fubon/public_html/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/fubon/public_html/node_modules/tslib/tslib.js:122:57)
[Nest] 1399   - 09/11/2021, 8:18:13 AM   [TypeOrmModule] Unable to connect to the database. Retrying (7)... +3007ms
Error: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ryancms'@'localhost' to database 'ryancms'
    at Handshake.Sequence._packetToError (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    --------------------
    at Protocol._enqueue (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/fubon/public_html/node_modules/mysql/lib/Pool.js:48:16)
    at /home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:884:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:881:16)
    at MysqlDriver.<anonymous> (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:343:36)
    at step (/home/fubon/public_html/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/fubon/public_html/node_modules/tslib/tslib.js:122:57)
[Nest] 1399   - 09/11/2021, 8:18:16 AM   [TypeOrmModule] Unable to connect to the database. Retrying (8)... +3009ms
Error: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ryancms'@'localhost' to database 'ryancms'
    at Handshake.Sequence._packetToError (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    --------------------
    at Protocol._enqueue (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/fubon/public_html/node_modules/mysql/lib/Pool.js:48:16)
    at /home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:884:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:881:16)
    at MysqlDriver.<anonymous> (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:343:36)
    at step (/home/fubon/public_html/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/fubon/public_html/node_modules/tslib/tslib.js:122:57)
[Nest] 1399   - 09/11/2021, 8:18:19 AM   [TypeOrmModule] Unable to connect to the database. Retrying (9)... +3008ms
Error: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ryancms'@'localhost' to database 'ryancms'
    at Handshake.Sequence._packetToError (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    --------------------
    at Protocol._enqueue (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/fubon/public_html/node_modules/mysql/lib/Pool.js:48:16)
    at /home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:884:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:881:16)
    at MysqlDriver.<anonymous> (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:343:36)
    at step (/home/fubon/public_html/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/fubon/public_html/node_modules/tslib/tslib.js:122:57)
[Nest] 1399   - 09/11/2021, 8:18:19 AM   [ExceptionHandler] ER_DBACCESS_DENIED_ERROR: Access denied for user 'ryancms'@'localhost' to database 'ryancms' +3ms
Error: ER_DBACCESS_DENIED_ERROR: Access denied for user 'ryancms'@'localhost' to database 'ryancms'
    at Handshake.Sequence._packetToError (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    --------------------
    at Protocol._enqueue (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/fubon/public_html/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/fubon/public_html/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/fubon/public_html/node_modules/mysql/lib/Pool.js:48:16)
    at /home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:884:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:881:16)
    at MysqlDriver.<anonymous> (/home/fubon/public_html/src/driver/mysql/MysqlDriver.ts:343:36)
    at step (/home/fubon/public_html/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/fubon/public_html/node_modules/tslib/tslib.js:122:57)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@webuzo:/home/fubon/public_html# 
```

**Comment by m-Ryan** [comment]
Please check the config of database in `app/app.module.ts`, 

```ts

const ormConfig = {
  type: "mysql",
  host: process.env.MAIN_SERVER,
  port: 3306,
  username: process.env.MYSQL_USER_NAME,
  password: process.env.MYSQL_PASSWORD,
  database: "cms",
  entities: ["**/**.entity{.ts,}"],
  synchronize: true,
  cache: true,
  logging: false,
};
```

**Comment by thefubon** [comment]
Everything is fine in the local environment. does not work on a ubuntu 18.4 server

**Comment by m-Ryan** [comment]
What's wrong?
